name: Project Setup 
description: Checkout code and cache dependencies

inputs:
    project-type:
        description: frontend | backend
        required: true
    node-version:
        description: Node.js version to setup
        required: true
    dotnet-version:
        description: DotNet version to setup
        required: true
    cache-dependency-path:
        description: Path to cache dependencies (like node_modules, ~/.m2/repository, etc.)
        required: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - if: ${{ inputs.project-type == 'frontend'}}
      name: setup node
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - if: ${{ inputs.project-type == 'backend'}}
      name: setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        cache: true
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - if: ${{ inputs.project-type == 'backend'}}
      name: Restore dependencies
      shell: bash
      run: dotnet restore

        





###################################################################################################

#   cache-key:
#     description: Base cache key
#     required: true
#     type: string
  
#   restore-keys:
#     description: Restore keys in case base cache hit fails
#     required: false
#     type: string

#   cache-path:
#     description: Path to cache (node_modules, ~/.m2, ~/.gradle, etc.)
#     required: true
#     type: string

#   lock-file:
#     description: Dependency lock file used for cache hashing
#     required: true
#     type: string

    # Cache dependencies
    # - name: Cache dependencies
    #   id: dependency-caching
    #   uses: actions/cache@v4
    #   env:
    #     cache-name: cache-node-modules
    #   with:
    #     path: ${{ inputs.cache-path }}
    #     key: ${{ inputs.cache-key }}-${{ env.cache-name }}-${{ hashFiles(inputs.lock-file) }}
    #     restore-keys: |
    #       ${{ inputs.restore-keys }}